language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
env:
  - CI=true
script:
  - npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
