name: Deploy CI

on:
  push:
    branches:
      - feature/github-action

jobs:
  build-and-deploy:
    # 服务器环境
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: yarn install

      - name: build & deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_SCRIPT: yarn run docs:build
          BRANCH: gh-pages
          FOLDER: 'dist/'
