name: Deploy CI

on:
  push:
    branches:
      - feature/github-action

jobs:
  build-and-deploy:
    # 服务器环境
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: yarn install

      - name: build
        run: yarn run docs:build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@master
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
